import { allRows, firstRow, nowIso, runStatement } from "../../db/index.ts";
import { readResponseText } from "./bounded-body.ts";
import { sha256Hex } from "./secure-token.ts";
import { BUSINESS_CONTENT, SERVICE_CONTENT, serviceDefinition, type BusinessContentKey } from "./whatsapp-content.ts";
import { TwilioSendError } from "./twilio-send.ts";
import { d1Database, twilioSendRuntime, type TwilioSendRuntime } from "./runtime-env.ts";

const SID = /^HX[0-9a-f]{32}$/i;
function canonical(value: unknown): string {
  if(value===undefined) return "undefined";
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  if (value && typeof value === "object") return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonical(Reflect.get(value,key))}`).join(",")}}`;
  return JSON.stringify(value) ?? "null";
}
// Twilio adds RCS-only presentation defaults when reading a card back. They do
// not change WhatsApp content; keep every text, media and action value strict.
function whatsappShape(value:unknown):unknown {
  if(!value || typeof value!=='object' || Array.isArray(value)) return value;
  const copy=structuredClone(value) as Record<string,unknown>;
  const types=copy.types;
  if(types && typeof types==='object') {
    // Authentication body is generated by WhatsApp and cannot be customized.
    // Its actual controls (expiry, security notice and Copy Code) stay strict.
    const authentication=Reflect.get(types,'whatsapp/authentication');
    if(authentication && typeof authentication==='object' && typeof Reflect.get(authentication,'body')==='string') {
      Reflect.deleteProperty(authentication,'body');
    }
    // URL actions navigate by type/title/url, not a quick-reply payload. Twilio
    // adds an ID on readback; ignore only that scalar annotation for URL CTAs.
    const cta=Reflect.get(types,'twilio/call-to-action');
    const ctaActions=cta && typeof cta==='object' ? Reflect.get(cta,'actions') : null;
    if(Array.isArray(ctaActions)) for(const action of ctaActions) {
      if(!action || typeof action!=='object' || Reflect.get(action,'type')!=='URL') continue;
      const id=Reflect.get(action,'id');
      if(id===null || (typeof id==='string' && id.length<=200) || Number.isSafeInteger(id)) Reflect.deleteProperty(action,'id');
    }
    const card=Reflect.get(types,'twilio/card');
    if(card && typeof card==='object') {
      for(const key of ['body','subtitle','orientation','thumbnailImageAlignment','height']) {
        if(Reflect.get(card,key)===null) Reflect.deleteProperty(card,key);
      }
      for(const [key,allowed] of Object.entries({orientation:['VERTICAL','HORIZONTAL'],thumbnailImageAlignment:['LEFT','RIGHT'],height:['SHORT','MEDIUM','TALL']})) {
        if(allowed.includes(String(Reflect.get(card,key)))) Reflect.deleteProperty(card,key);
      }
      const actions=Reflect.get(card,'actions');
      if(Array.isArray(actions)) for(const action of actions) {
        if(action && typeof action==='object' && (Reflect.get(action,'chip_list')===null || typeof Reflect.get(action,'chip_list')==='boolean')) Reflect.deleteProperty(action,'chip_list');
        // Content readback adds an index annotation which may use a default
        // independently of array position. It is not a creation input here;
        // the array order, IDs and labels are still compared exactly below.
        if(action && typeof action==='object' && (Reflect.get(action,'index')===null || /^\d$/.test(String(Reflect.get(action,'index'))))) Reflect.deleteProperty(action,'index');
      }
    }
  }
  return copy;
}
function differingPaths(expected:unknown,actual:unknown,path=''):string[] {
  if(canonical(expected)===canonical(actual)) return [];
  if(expected && actual && typeof expected==='object' && typeof actual==='object') {
    return [...new Set([...Object.keys(expected),...Object.keys(actual)])].flatMap(key=>
      differingPaths(Reflect.get(expected,key),Reflect.get(actual,key),`${path}/${key}`)).slice(0,30);
  }
  return [path];
}
async function api(runtime:TwilioSendRuntime,path:string,body?:unknown,fetcher:typeof fetch=fetch):Promise<Record<string,unknown>> {
  const url=new URL(path,"https://content.twilio.com");
  if(url.origin!=="https://content.twilio.com" || url.username || url.password) throw new Error("Invalid Twilio content origin.");
  const response=await fetcher(url,{method:body?"POST":"GET",headers:{Authorization:`Basic ${btoa(`${runtime.accountSid}:${runtime.authToken}`)}`,
    Accept:"application/json",...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,redirect:"manual",signal:AbortSignal.timeout(8_000)});
  const raw=await readResponseText(response,1024*1024);
  if(!response.ok) throw new TwilioSendError(`twilio_content_http_${response.status}`,"Twilio content operation failed.",{retryable:response.status>=500 || response.status===429});
  const value:unknown=JSON.parse(raw);
  if(!value || typeof value!=="object" || Array.isArray(value)) throw new Error("Invalid Twilio content response.");
  const account=Reflect.get(value,"account_sid");
  if(account && account!==runtime.accountSid) throw new Error("Wrong Twilio account.");
  return value as Record<string,unknown>;
}

export async function ensureServiceContent(db:D1Database,runtime:TwilioSendRuntime,key:string,fetcher:typeof fetch=fetch):Promise<string> {
  const definition=serviceDefinition(key);
  const registryKey=`service:${definition.friendly_name}`;
  return ensureContent(db,runtime,definition,registryKey,fetcher);
}

export async function ensureBusinessContent(db:D1Database,runtime:TwilioSendRuntime,key:BusinessContentKey,fetcher:typeof fetch=fetch):Promise<string> {
  const definition=BUSINESS_CONTENT[key].content;
  return ensureContent(db,runtime,definition,`business:${definition.friendly_name}`,fetcher);
}

async function ensureContent(db:D1Database,runtime:TwilioSendRuntime,definition:{friendly_name:string;language:string;variables:object;types:object},registryKey:string,fetcher:typeof fetch):Promise<string> {
  const hash=await sha256Hex(canonical(definition));
  const at=nowIso();
  await runStatement(db,`INSERT OR IGNORE INTO med250_twilio_content_registry(definition_key,definition_hash,state,updated_at) VALUES (?,?,'missing',?)`,[registryKey,hash,at]);
  const row=await firstRow(db,`SELECT * FROM med250_twilio_content_registry WHERE definition_key=?`,[registryKey]);
  if(!row || row.definition_hash!==hash) throw new Error("Version the changed WhatsApp content definition.");
  if(typeof row.content_sid==="string" && SID.test(row.content_sid)) return row.content_sid;
  const lease=crypto.randomUUID();
  const claimed=await runStatement(db,`UPDATE med250_twilio_content_registry SET lease_token=?,lease_expires_at=?,state='creating',updated_at=?
    WHERE definition_key=? AND content_sid IS NULL AND (lease_expires_at IS NULL OR lease_expires_at<=?)`,[lease,new Date(Date.now()+60_000).toISOString(),at,registryKey,at]);
  if(!claimed.meta.changes) throw new TwilioSendError("service_template_preparing","Service template is being prepared.",{retryable:true});
  try {
    let found:Record<string,unknown>|null=null;
    // A lost creation receipt must be reconciled, never blindly recreated.
    if(row.state!=="missing") {
      let page:string|null="/v1/Content?PageSize=500";
      for(let n=0;page && n<20;n++) {
        const result=await api(runtime,page,undefined,fetcher);
        const contents=Array.isArray(result.contents)?result.contents:[];
        const matches=contents.filter((item):item is Record<string,unknown>=>Boolean(item&&typeof item==="object"&&Reflect.get(item,"friendly_name")===definition.friendly_name));
        if(matches.length>1 || (found&&matches.length)) throw new Error("Ambiguous service content name.");
        found=matches[0]??found;
        const meta=result.meta;
        page=meta&&typeof meta==="object"&&typeof Reflect.get(meta,"next_page_url")==="string"?Reflect.get(meta,"next_page_url"):null;
      }
      if(page) throw new TwilioSendError("service_template_list_limit","Content reconciliation exceeded its bounded page limit.",{retryable:false});
      if(!found) throw new TwilioSendError("service_template_creation_unconfirmed","A previous content creation needs reconciliation.",{retryable:false});
    }
    const content=found??await api(runtime,"/v1/Content",definition,fetcher);
    const sid=content.sid;
    if(typeof sid!=="string"||!SID.test(sid)) throw new Error("Invalid content SID.");
    const shape={friendly_name:content.friendly_name,language:content.language,variables:content.variables??{},types:content.types??{}};
    if(canonical(whatsappShape(shape))!==canonical(whatsappShape(definition))) {
      await runStatement(db,"UPDATE med250_twilio_content_registry SET rejection_reason=? WHERE definition_key=? AND lease_token=?",
        [`definition_mismatch:${differingPaths(whatsappShape(definition),whatsappShape(shape)).join(',')}`.slice(0,2000),registryKey,lease]);
      throw new Error("Twilio service content differs from reviewed definition.");
    }
    await runStatement(db,`UPDATE med250_twilio_content_registry SET content_sid=?,state='ready',rejection_reason=NULL,lease_token=NULL,lease_expires_at=NULL,checked_at=?,updated_at=? WHERE definition_key=? AND lease_token=?`,[sid,at,at,registryKey,lease]);
    return sid;
  } catch(error) {
    const definitiveRejection=error instanceof TwilioSendError && /^twilio_content_http_(400|401|403|422|429)$/.test(error.code) && row.state==='missing';
    await runStatement(db,`UPDATE med250_twilio_content_registry SET state=?,lease_token=NULL,lease_expires_at=NULL,updated_at=? WHERE definition_key=? AND lease_token=?`,[definitiveRejection?'missing':'creation_unconfirmed',nowIso(),registryKey,lease]);
    throw error;
  }
}

export async function readApproval(db:D1Database,runtime:TwilioSendRuntime,sid:string,fetcher:typeof fetch=fetch):Promise<string> {
  if(!SID.test(sid)) throw new Error("Invalid approval SID.");
  let value:Record<string,unknown>;
  try {value=await api(runtime,`/v1/Content/${sid}/ApprovalRequests`,undefined,fetcher);}
  catch(error) {if(error instanceof TwilioSendError && error.code==='twilio_content_http_404') value={};else throw error;}
  const whatsapp=value.whatsapp;
  const status=whatsapp&&typeof whatsapp==="object"?String(Reflect.get(whatsapp,"status")??"unsubmitted").toLowerCase():"unsubmitted";
  const reason=whatsapp&&typeof whatsapp==="object"?String(Reflect.get(whatsapp,"rejection_reason")??"").slice(0,2000):"";
  const at=nowIso();
  await runStatement(db,`INSERT INTO med250_twilio_content_registry(definition_key,content_sid,state,approval_status,rejection_reason,checked_at,updated_at)
    VALUES (?,?,'observed',?,?,?,?) ON CONFLICT(definition_key) DO UPDATE SET approval_status=excluded.approval_status,
    rejection_reason=excluded.rejection_reason,checked_at=excluded.checked_at,updated_at=excluded.updated_at`,[`approval:${sid}`,sid,status,reason,at,at]);
  return status;
}

export async function verifyBusinessDefinition(runtime:TwilioSendRuntime,sid:string,key:BusinessContentKey,fetcher:typeof fetch=fetch):Promise<void> {
  if(!SID.test(sid)) throw new Error('Invalid content SID.');
  const content=await api(runtime,`/v1/Content/${sid}`,undefined,fetcher);
  const shape={friendly_name:content.friendly_name,language:content.language,variables:content.variables??{},types:content.types??{}};
  if(canonical(whatsappShape(shape))!==canonical(whatsappShape(BUSINESS_CONTENT[key].content)))
    throw new TwilioSendError('template_definition_mismatch','Business template differs from the reviewed definition.',{retryable:false});
}

export async function verifyPharmacyContent(runtime:TwilioSendRuntime,sid:string,kind:string,variables:Record<string,string>,fetcher:typeof fetch=fetch,initial=false):Promise<void> {
  if(!SID.test(sid)) throw new Error("Invalid content SID.");
  const content=await api(runtime,`/v1/Content/${sid}`,undefined,fetcher);
  const types=Reflect.get(whatsappShape(content) as object,'types');
  const card=types&&typeof types==='object'?Reflect.get(types,'twilio/card'):null;
  const image=kind==='client_media_request';
  const title=card&&typeof card==='object'?Reflect.get(card,'title'):null;
  const actions=card&&typeof card==='object'?Reflect.get(card,'actions'):null;
  const media=card&&typeof card==='object'?Reflect.get(card,'media'):null;
  const expectedCard=BUSINESS_CONTENT[image?(initial?'image_initial':'image'):(initial?'web_initial':'web')].content.types['twilio/card'];
  const expectedActions=expectedCard.actions;
  const expectedMedia=`https://med-250.com/whatsapp-${image?'client':'order'}-media/{{${image?'5':'7'}}}.png`;
  const rendered=typeof title==='string'?title.replace(/\{\{(\d+)\}\}/g,(_match,key:string)=>variables[key]??'{{missing}}'):'';
  if(title!==expectedCard.title || !rendered || rendered.length>1024 || rendered.includes('{{') || canonical(actions)!==canonical(expectedActions)
    || canonical(media)!==canonical([expectedMedia])) {
    throw new TwilioSendError('template_definition_mismatch','Pharmacy template does not match the approved action/media contract.',{retryable:false});
  }
}

export async function syncWhatsAppContent(env:Env):Promise<void> {
  const db=d1Database(env),runtime=twilioSendRuntime(env);
  // Bound each scheduled batch. No patient content or phone-number variables go into these definitions.
  let prepared=0;
  for(const key of Object.keys(SERVICE_CONTENT)) {
    const row=await firstRow(db,`SELECT content_sid,updated_at FROM med250_twilio_content_registry WHERE definition_key=?`,[`service:${serviceDefinition(key).friendly_name}`]);
    if(!row?.content_sid && row?.updated_at && Date.now()-Date.parse(String(row.updated_at))<5*60_000) continue;
    if(!row?.content_sid) {
      try {await ensureServiceContent(db,runtime,key);} catch(error) {console.error(JSON.stringify({event:"service_content_setup_failed",key,errorType:error instanceof Error?error.name:"Error"}));}
      if(++prepared>=3) break;
    }
  }
  // One explicitly versioned business template per run. Never delete/recreate a
  // sender, resubmit a rejection, or retry an ambiguous approval POST blindly.
  const checks=await allRows(db,"SELECT definition_key,checked_at FROM med250_twilio_content_registry WHERE definition_key LIKE 'business:%'");
  const lastCheck=(key:BusinessContentKey)=>String(checks.find(row=>row.definition_key===`business:${BUSINESS_CONTENT[key].content.friendly_name}`)?.checked_at??'');
  const businessKeys=(Object.keys(BUSINESS_CONTENT) as BusinessContentKey[]).sort((a,b)=>lastCheck(a).localeCompare(lastCheck(b)));
  for(const key of businessKeys) {
    const definition=BUSINESS_CONTENT[key];
    const registryKey=`business:${definition.content.friendly_name}`;
    const row=await firstRow(db,`SELECT * FROM med250_twilio_content_registry WHERE definition_key=?`,[registryKey]);
    if(row?.checked_at && Date.now()-Date.parse(String(row.checked_at))<60_000) continue;
    try {
      const sid=await ensureBusinessContent(db,runtime,key);
      const status=await readApproval(db,runtime,sid);
      if(status==='unsubmitted') {
        const claim=await runStatement(db,`UPDATE med250_twilio_content_registry SET approval_status='submitting',updated_at=?
          WHERE definition_key=? AND approval_status IS NULL`,[nowIso(),registryKey]);
        if(claim.meta.changes) {
          await api(runtime,`/v1/Content/${sid}/ApprovalRequests/whatsapp`,{name:definition.content.friendly_name,category:definition.category});
          await runStatement(db,`UPDATE med250_twilio_content_registry SET approval_status='submitted',checked_at=?,updated_at=? WHERE definition_key=?`,[nowIso(),nowIso(),registryKey]);
        }
      } else await runStatement(db,`UPDATE med250_twilio_content_registry SET approval_status=?,checked_at=?,updated_at=? WHERE definition_key=?`,[status,nowIso(),nowIso(),registryKey]);
    } catch(error) {console.error(JSON.stringify({event:'business_content_setup_failed',key,errorType:error instanceof Error?error.name:'Error',
      errorCode:error instanceof TwilioSendError?error.code:'definition_or_persistence_error'}));}
    finally {await runStatement(db,"UPDATE med250_twilio_content_registry SET checked_at=? WHERE definition_key=?",[nowIso(),registryKey]);}
    break;
  }
  const sids=[runtime.pharmacyClientMediaContentSid,runtime.pharmacyRequestContentSid,runtime.customerOtpContentSid,
    "HX4c2a1289aeeaf9b7d75782f3ff617aa9","HXc40fbd759da820c338972f0f0e8c4a09"];
  for(const sid of new Set(sids)) {
    const row=await firstRow(db,`SELECT checked_at FROM med250_twilio_content_registry WHERE definition_key=?`,[`approval:${sid}`]);
    if(row?.checked_at && Date.now()-Date.parse(String(row.checked_at))<3600_000) continue;
    try {await readApproval(db,runtime,sid);} catch(error) {console.error(JSON.stringify({event:"template_approval_read_failed",sid,errorType:error instanceof Error?error.name:"Error"}));}
    break;
  }
}
