import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { loadCloudflareBuildEnvironment } from "../scripts/build-cloudflare-environment.mjs";

test("production builds derive every browser integration variable from wrangler config", async () => {
  const environment = await loadCloudflareBuildEnvironment("production");
  assert.equal(environment.NEXT_PUBLIC_MED250_DEPLOYMENT_MODE, "live");
  assert.equal(environment.NEXT_PUBLIC_MED250_DEPLOYMENT_ORIGIN, "https://med-250.com");
  assert.match(environment.NEXT_PUBLIC_SUPABASE_URL, /^https:\/\/[a-z]+\.supabase\.co$/);
  assert.match(environment.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY, /^sb_publishable_/);
  assert.match(environment.NEXT_PUBLIC_TURNSTILE_SITE_KEY, /^0x4/);
});

test("the legacy Cloudflare build uses the same canonical live browser contract", async () => {
  const [legacy, production] = await Promise.all([
    loadCloudflareBuildEnvironment("gikundiro"),
    loadCloudflareBuildEnvironment("production"),
  ]);
  assert.deepEqual(legacy, production);
});

test("Cloudflare build wrapper rejects unknown environments", async () => {
  await assert.rejects(loadCloudflareBuildEnvironment("preview"), /Unsupported Cloudflare build environment/);
});

test("Worker runtime bindings are request-scoped and production tracing is sampled", async () => {
  const [runtimeEnvironment, worker, wrangler, generatedTypes] = await Promise.all([
    readFile(new URL("../lib/runtime-environment.ts", import.meta.url), "utf8"),
    readFile(new URL("../worker/index.ts", import.meta.url), "utf8"),
    readFile(new URL("../wrangler.jsonc", import.meta.url), "utf8"),
    readFile(new URL("../worker-configuration.d.ts", import.meta.url), "utf8"),
  ]);
  assert.match(runtimeEnvironment, /new AsyncLocalStorage<Med250RuntimeEnvironment>/);
  assert.doesNotMatch(runtimeEnvironment, /globalThis|__MED250_RUNTIME_ENVIRONMENT__/);
  assert.match(worker, /runWithMed250RuntimeEnvironment\(env/);
  assert.match(worker, /type Env = Omit<Cloudflare\.Env/);
  assert.match(wrangler, /"traces": \{ "enabled": true, "head_sampling_rate": 0\.05 \}/);
  assert.match(generatedTypes, /Generated by Wrangler/);
  assert.match(generatedTypes, /interface Env extends __BaseEnv_Env/);
});
